import { type CSSProperties } from 'react'
import { ArrowDownToLine, ArrowLeft, ArrowUpRight, RefreshCw, Sparkles } from 'lucide-react'
import type { AppMode, CreativeDirection } from '../types'

export function ResultStage({
  originalUrl,
  resultUrl,
  direction,
  mode,
  comparison,
  onComparisonChange,
  onGenerateAnother,
  onDownload,
  onStartOver,
}: {
  originalUrl: string
  resultUrl: string
  direction: CreativeDirection
  mode: AppMode
  comparison: number
  onComparisonChange: (value: number) => void
  onGenerateAnother: () => void
  onDownload: () => void
  onStartOver: () => void
}) {
  return (
    <section className="result-stage" aria-labelledby="result-heading">
      <div className="result-heading-row">
        <div>
          <div className="eyebrow"><span className="eyebrow-dot" /> STEP 05 · YOUR PRODUCT, REFRAMED</div>
          <h2 id="result-heading">A fresh point of view.</h2>
          <p className="stage-intro">{direction.title} <span className="inline-dot">·</span> {direction.visualDirection}</p>
        </div>
        <span className={`result-mode ${mode === 'demo' ? 'result-mode--demo' : 'result-mode--live'}`}>
          <Sparkles size={14} /> {mode === 'demo' ? 'Studio preview · demo mode' : 'AI-generated image'}
        </span>
      </div>

      {mode === 'demo' && (
        <div className="demo-result-notice" role="status">
          <span className="demo-notice-dot" /> This is a styled preview using your original photo — it was not generated by AI.
        </div>
      )}

      <div className="compare-card panel">
        <div className="compare-image" style={{ '--compare-position': `${comparison}%` } as CSSProperties}>
          <img className="compare-image__after" src={resultUrl} alt={mode === 'demo' ? `Demo studio composition in the ${direction.title} direction` : `AI-generated ${direction.title} product photograph`} />
          <div className="compare-image__before-wrap">
            <img src={originalUrl} alt="Original uploaded product photograph" />
          </div>
          <span className="compare-label compare-label--before">ORIGINAL</span>
          <span className="compare-label compare-label--after">{mode === 'demo' ? 'STUDIO PREVIEW' : 'NEW IMAGE'}</span>
          <span className="compare-divider" aria-hidden="true"><span><ArrowLeft size={12} /><ArrowUpRight size={12} /></span></span>
        </div>
        <div className="compare-controls">
          <span>BEFORE</span>
          <input
            aria-label="Compare original and result"
            type="range"
            min="0"
            max="100"
            value={comparison}
            onChange={(event) => onComparisonChange(Number(event.currentTarget.value))}
          />
          <span>AFTER</span>
        </div>
      </div>

      <div className="result-actions">
        <button className="button button--dark" type="button" onClick={onDownload}><ArrowDownToLine size={16} /> Download image</button>
        <button className="button button--outline" type="button" onClick={onGenerateAnother}><RefreshCw size={15} /> Generate another</button>
        <button className="text-button" type="button" onClick={onStartOver}>Start over <ArrowUpRight size={15} /></button>
      </div>
    </section>
  )
}
